package com.pas.game.status;

/** 상태효과를 HUD용 짧은 한글 표기로 변환한다. */
public final class StatusDisplay {
    private StatusDisplay(){}
    public static String label(StatusType type){switch(type){case SELF_STUN:return "기절";case HUNT_TURN_SKIP:return "턴 건너뛰기";case DAZED:return "멍해짐";case STIFF:return "경직";case BIND:return "구속";case UNSTOPPABLE:return "저지불가";case POISON:return "중독";case FIRE:return "화염";case SHARP:return "예리함";case DAMAGE_REDUCTION:return "피해감소";case CRIT_RATE_UP:return "치명타↑";case EVADE_UP:return "회피↑";case TAUNT:return "도발";case ATTACK_FLAT_UP:case ATTACK_UP:return "공격력↑";case DEFENSE_FLAT_UP:return "방어력↑";case MAX_HP_UP:return "최대 HP↑";case INVINCIBLE_DIRECT:return "무적";case PURIFICATION_STACK:case PURIFICATION_EXECUTION:return "정화";case DIVINE_FRAGMENT:return "신성의 파편";case DIVINE_PUNISHMENT:return "신벌";case DAMAGE_TAKEN_UP:return "받는피해↑";case GUARDIAN_AURA:return "수호의 오라";case JUSTICE_DOT:return "심판";case RECOIL_AT_TURN_END:return "반동";case MOVEMENT_DISABLED:return "이동불가";case EVASION_DISABLED:return "회피불가";case FLAT_DAMAGE_REDUCTION:return "피해차감";case DOT_DAMAGE_TWICE:return "지속 피해 2회";case EMERGENCY_ESCAPE_READY:return "비상 탈출 대기";case MANA_ACTIVE:return "마력";case HIT_CHANCE_REDUCTION:return "명중률↓";case DEVOUR:return "포식";case SKILL_HEAVY_ARMOR:return "중갑";case ABYSSAL_MARK:return "심연의 낙인";case DOUBLE_CAST:return "이중 영창";case EXISTENCE_LOAN:return "존재 대여";case DIMENSIONAL_DRIFT:return "차원 표류";case PAST_ECHO:return "과거의 잔상";default:return type.name();}}
    public static boolean isDebuff(StatusType type){switch(type){case SELF_STUN:case HUNT_TURN_SKIP:case DAZED:case STIFF:case BIND:case POISON:case FIRE:case TAUNT:case DAMAGE_TAKEN_UP:case JUSTICE_DOT:case RECOIL_AT_TURN_END:case MOVEMENT_DISABLED:case EVASION_DISABLED:case DOT_DAMAGE_TWICE:case PURIFICATION_EXECUTION:case DIVINE_PUNISHMENT:case ABYSSAL_MARK:return true;default:return false;}}
    public static String compactValue(StatusEffect effect){StatusType type=effect.getType();String value;if(type==StatusType.EMERGENCY_ESCAPE_READY)value=(int)effect.getMagnitude()+"번 칸";else if(type==StatusType.FIRE||type==StatusType.POISON)value=format(effect.getMagnitude());else if(type.getValueKind()!=StatusType.ValueKind.DURATION&&effect.getMagnitude()!=0)value=format(effect.getMagnitude())+type.getValueSuffix()+(effect.isPermanent()?"":" · "+effect.getRemainingTurns()+"T");else value=effect.isPermanent()?"":effect.getRemainingTurns()+"T";return effect.getStackCount()>1?value+"×"+effect.getStackCount():value;}
    public static String description(StatusEffect effect){String suffix=effect.getType().getValueSuffix();String kind;switch(effect.getType().getValueKind()){case PERCENT:kind="비율";break;case PERCENTAGE_POINT:kind="확률 포인트";break;case FLAT:kind="수치";break;default:kind="지속시간";}String duration=effect.isPermanent()?"":"\n남은 턴: "+effect.getRemainingTurns();String rule;if(effect.getType()==StatusType.SELF_STUN)rule="\n다음 자기 턴 전체를 건너뜁니다.";else if(effect.getType()==StatusType.HUNT_TURN_SKIP)rule="\n다음 자기 턴을 이 횟수만큼 건너뜁니다. 저지불가로 막을 수 없습니다.";else if(effect.getType()==StatusType.GUARDIAN_AURA)rule="\n인접한 아군이 받는 피해를 "+format(effect.getMagnitude())+"만큼 감소시킵니다.";else if(effect.getType()==StatusType.FIRE)rule="\n화염 피해를 받은 뒤 다음 턴까지 화염이 추가되지 않으면, 피해를 받은 후 화염 수치가 5% 감소합니다. 감소 계산의 소수점 이하는 버립니다.";else if(effect.getType()==StatusType.PURIFICATION_STACK)rule="\n피해를 가한 뒤 이 수치가 대상의 남은 HP 이상이면 정화가 전부 대상에게 옮겨집니다.";else if(effect.getType()==StatusType.PURIFICATION_EXECUTION)rule="\n이 대상의 턴 종료 시 즉사합니다. 해제할 수 없으며 무적과 저지불가를 무시합니다.";else if(effect.getType()==StatusType.DIVINE_PUNISHMENT)rule="\n성직자가 획득할 정화 1마다 현재 HP와 최대 HP가 각각 1 감소합니다. 대상이 죽으면 종료됩니다.";else if(effect.getType()==StatusType.INVINCIBLE_DIRECT)rule="\n일반 피해만 막습니다. 지속 피해, 반동, 정화 처형과 신벌은 막지 못합니다.";else if(effect.getType()==StatusType.DIVINE_FRAGMENT)rule="\n싱글에서는 일반 피해 무적과 저지불가를 얻습니다. 멀티에서는 사거리 2 안에서 턴을 시작한 우호적 대상이 HP 300을 회복합니다.";else if(effect.getType()==StatusType.MANA_ACTIVE)rule="\n현재 마법사 턴에 사용하는 스킬의 명시된 부가효과를 강화합니다.";else if(effect.getType()==StatusType.HIT_CHANCE_REDUCTION)rule="\n자신을 공격하는 적의 명중률을 "+format(effect.getMagnitude())+"%p 낮춥니다. 다음 자신의 턴 시작 직전까지 유지됩니다.";else if(effect.getType()==StatusType.SKILL_HEAVY_ARMOR)rule="\n받는 일반 피해를 "+format(effect.getMagnitude())+"만큼 감소시킵니다.";else if(effect.getType()==StatusType.DEVOUR)rule="\n일반 피해를 무효화하고, 무효화 직전 피해의 "+format(effect.getMagnitude())+"%만큼 회복합니다.";else if(effect.getType()==StatusType.ABYSSAL_MARK)rule="\n아군이 일반 스킬 피해를 가하면 실제 피해를 준 유닛이 공격력의 "+format(effect.getMagnitude())+"%만큼 회복합니다. 한 스킬당 한 번만 발동합니다.";else if(effect.getType()==StatusType.DOUBLE_CAST)rule="\n다음 비궁극기 스킬이 이 수치만큼 추가 발동합니다.";else if(effect.getType()==StatusType.EXISTENCE_LOAN)rule="\n비궁극기 스킬을 사용할 때 선택한 부가효과를 이 수치만큼 추가 적용합니다.";else if(effect.getType()==StatusType.PAST_ECHO)rule="\n세 번째 다음 자기 턴 시작에 저장한 위치와 HP를 복원합니다. 사망한 경우 부활하지 않습니다.";else rule="";return label(effect.getType())+duration+"\n효과 수치: "+format(effect.getMagnitude())+suffix+" ("+kind+")"+rule+(effect.getStackCount()>1?"\n중첩: "+effect.getStackCount():"");}
    public static String gainText(StatusEffect effect){double value=effect.getMagnitude();switch(effect.getType()){case ATTACK_FLAT_UP:return "공격력 증가 "+format(value);case ATTACK_UP:return "공격력 "+format(value)+"% 증가";case DEFENSE_FLAT_UP:return "방어력 증가 "+format(value);case MAX_HP_UP:return "최대 HP 증가 "+format(value);case CRIT_RATE_UP:return "치명타율 "+format(value)+"%p 증가";default:return label(effect.getType())+(value==0?"":" "+format(value)+effect.getType().getValueSuffix());}}
    public static String barrierLabel(int amount){return "피해방어 "+Math.max(0,amount);}
    public static String barrierDescription(int amount){return "피해방어 수치: "+Math.max(0,amount)+"\n다음 한 번의 실제 피해를 해당 수치만큼 막습니다.\n한 번 막은 뒤에는 남은 수치와 관계없이 사라집니다.";}
    private static String format(double value){return value==(long)value?String.valueOf((long)value):String.format(java.util.Locale.US,"%.1f",value);}
}
